### ISSUE TITLE
Main page

### ISSUE THREAD

**Issue by echavemann** [FinRL-Contest/ACM_ICAIF_2023#1]
- Change Logo to below
- Title to ICAIF Contest or smthn
- Remove the NUTC main site link
- Rebind Learn More to Contest Info Page (#2)
- Update Picture when we get a chance

**Comment by stellawang196** [comment]
<img width="382" alt="FinRL Contest Logo" src="https://github.com/FinRL-Contest/icaif-nutc/assets/114252105/f95860c0-8dd0-4e87-a769-6ebc60d6e21a">

**Comment by andrlime** [comment]
Re: the above logo

Is there a square version to replace ones like this?
<img width="569" alt="image" src="https://github.com/FinRL-Contest/icaif-nutc/assets/54134293/b7108a25-0294-414b-861b-14f88f3a69d0">

**Comment by stellawang196** [comment]
![finrlcontest logo](https://github.com/FinRL-Contest/icaif-nutc/assets/114252105/3f64a377-e8db-4048-a09e-85a58fe2bd45)

**Comment by echavemann** [comment]
maybe we toss the words?

**Comment by stellawang196** [comment]
<img width="174" alt="finrlcontestlogo" src="https://github.com/FinRL-Contest/icaif-nutc/assets/114252105/990344ed-38e0-463f-9bf9-750e8b1c1a7e">

**Comment by andrlime** [comment]
Is there an svg version

**Comment by stellawang196** [comment]
![finrlcontestlogo](https://github.com/FinRL-Contest/icaif-nutc/assets/114252105/5fa9ecc0-8a0e-4d2e-8cf9-84e870e41e98)
is this one good?

**Comment by andrlime** [comment]
perfect
