### ISSUE TITLE
change references to NUTC domain

### ISSUE THREAD

**Issue by andrlime** [FinRL-Contest/ACM_ICAIF_2023#10]
Stuff like
<img width="459" alt="image" src="https://github.com/FinRL-Contest/icaif-nutc/assets/54134293/b6f532f8-db9d-468e-8b68-0ed1a465c067">

needs to be changed, but I don't know what that domain should be

**Comment by stellawang196** [comment]
I think the domain name should be github domain name, something like "https://unlearning-challenge.github.io/" (this is an example). @andrlime

**Comment by andrlime** [comment]
Sounds good

**Comment by stellawang196** [comment]
Will you create the github page or need I do this? @andrlime

**Comment by andrlime** [comment]
Actually I think since there's Firebase involved, we can just host with Firebase. Though, since this is a NextJS app, that does cost a small amount of money. I'm not sure how much. I don't know if it's possible to host a NextJS app on Github. It's something we can definitely look into.

**Comment by andrlime** [comment]
https://medium.com/frontendweb/how-to-deploy-a-nextjs-app-to-github-pages-1de4f6ed762e
Seems feasible, I can look into it tomorrow
