### ISSUE TITLE
Sign Up

### ISSUE THREAD

**Issue by echavemann** [FinRL-Contest/ACM_ICAIF_2023#3]
- remove resume upload
- add a team leader field for the Personal Information
- make School a short answer, not a drop down

**Comment by andrlime** [comment]
school should be "school" or maybe "institution" would be better?

**Comment by stellawang196** [comment]
yes, institution is better

**Comment by andrlime** [comment]
if we add team leader, does that change the shape of the data in the database? Are there changes that need to be made as a result of this

**Comment by andrlime** [comment]
<img width="486" alt="image" src="https://github.com/FinRL-Contest/icaif-nutc/assets/54134293/8ae419de-2436-423c-8030-0903850cc8f0">
We keeping this?

**Comment by stellawang196** [comment]
may be not
